schema/mysql-migrations/v0.9.1.sql, schema/mysql.sql
=> Fix time frames

application/controllers/TimeframeController.php, application/controllers/TimeframesController.php, library/Reporting/DivDecorator.php, library/Reporting/Web/DivDecorator.php, library/Reporting/Web/Flatpickr.php, library/Reporting/Web/Forms/DecoratedElement.php, library/Reporting/Web/Forms/ReportForm.php, library/Reporting/Web/Forms/ScheduleForm.php, library/Reporting/Web/Forms/SendForm.php, library/Reporting/Web/Forms/TimeframeForm.php, library/Reporting/Web/ReportsAndTimeframesTabs.php, public/js/module.js
=> Allow to manage time frames

library/Reporting/Web/Forms/ScheduleForm.php
=> Fix wrong class import in ScheduleForm

application/controllers/TimeframesController.php
'New Timerfame' -> 'New Timeframe'
=> Fix typo in TimeframesController.php

schema/mysql.sql
Placed table template above other tables
=> Changed schema procedure

doc/02-Installation.md, library/Reporting/Web/Forms/TimeframeForm.php, schema/postgresql.sql
=> Support PostgreSQL

library/Reporting/Actions/SendMail.php
=> SendMail: Properly export reports to PDF

library/Reporting/Actions/SendMail.php, library/Reporting/Mail.php, library/Reporting/Web/Forms/SendForm.php
=> Make subject configurable per schedule

application/controllers/ReportController.php, application/controllers/ReportsController.php, application/controllers/TemplatesController.php, application/controllers/TestController.php, application/controllers/TimeframeController.php, application/controllers/TimeframesController.php
refs https://github.com/Icinga/ipl-web/pull/72
=> Adjust calls to CompatController::setTitle()

application/controllers/ReportController.php
=> Increase resources when producing reports

application/forms/SelectBackendForm.php, doc/02-Installation.md, doc/03-Configuration.md
=> Enhance documentation

library/Reporting/Actions/SendMail.php
=> Support whitespace and comma separated e-mail recipients

library/Reporting/Database.php
=> Only use `PDO::MYSQL_ATTR_INIT_COMMAND` for mysql connections

application/controllers/ReportController.php, application/controllers/ReportsController.php, application/controllers/TemplateController.php, application/controllers/TemplatesController.php, application/controllers/TimeframeController.php, application/controllers/TimeframesController.php, configuration.php, doc/03-Configuration.md
=> Permissions

README.md
=> README.md: Clarify how to get sla reports with icingadb

library/Reporting/Scheduler.php
The use of `$interval` has been removed and `$next->modify($modify)` is used in `$loop` callback.
[ref/IP/41334](https://rt.icinga.com/Ticket/Display.html?id=41334)
fixes #135
=> Fix `Scheduler` for monthly reports

library/Reporting/Actions/SendMail.php
=> SendMail: Always read email address from disk

doc/02-Installation.md
The install docs are missing the `CREATE` permission
=> 02-Installation.md: fix SQL GRANT example

application/controllers/ReportController.php, application/controllers/TemplatesController.php, application/controllers/TestController.php, library/Reporting/Web/Forms/ReportForm.php, library/Reporting/Web/Forms/ScheduleForm.php, library/Reporting/Web/Forms/SendForm.php, library/Reporting/Web/Forms/TemplateForm.php, library/Reporting/Web/Forms/TimeframeForm.php
=> Add missing forms & controllers localization

library/Reporting/Web/Forms/TemplateForm.php
=> Fix Template discarding Images after editing

application/controllers/ReportController.php, library/Reporting/Web/Forms/ReportForm.php
=> Support cloning reports

application/controllers/ReportsController.php
- https://github.com/Icinga/icingadb-web/pull/655
=> Handle Icinga DB Web host/service actions

application/controllers/ReportsController.php, application/controllers/TemplatesController.php, application/controllers/TimeframesController.php
=> Add sort control for reports, templates and timeframes

library/Reporting/Report.php
-  https://github.com/Icinga/icingadb-web/pull/678
=> Include total averages of sla reports in `CSV` & `JSON` exports

doc/80-Upgrading.md, schema/mysql-upgrades/1.0.0.sql
=> Fix migrate schedule config procedure

application/clicommands/DownloadCommand.php, application/clicommands/ListCommand.php, application/clicommands/ScheduleCommand.php, application/controllers/ReportController.php, application/controllers/ReportsController.php, application/controllers/TemplateController.php, application/controllers/TemplatesController.php, application/controllers/TimeframeController.php, application/controllers/TimeframesController.php, library/Reporting/Cli/Command.php, library/Reporting/Database.php, library/Reporting/ProvidedHook/DbMigration.php, library/Reporting/Report.php, library/Reporting/Timeframe.php, library/Reporting/Web/Forms/ReportForm.php, library/Reporting/Web/Forms/ScheduleForm.php, library/Reporting/Web/Forms/SendForm.php, library/Reporting/Web/Forms/TemplateForm.php, library/Reporting/Web/Forms/TimeframeForm.php, library/Reporting/Web/Widget/Template.php
=> Make `Database` trait a singleton

doc/80-Upgrading.md, schema/mysql.schema.sql, schema/pgsql-upgrades/1.0.3.sql, schema/pgsql.schema.sql
=> Fix database schema

library/Reporting/Web/Widget/CoverPage.php
=> CoverPage: Fix deprecation message
